[project]
name = "warehouse-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.125.0",
    "jinja2>=3.1.6",
    "pydantic>=2.12.5",
    "uvicorn>=0.38.0",
]
